create table Items (Item_id NUMBER GENERATED by default on null as IDENTITY,ItemSerialNumber number not null,ItemName varchar(250) not null unique, MigratedTS Timestamp(3) default sysdate not null,LastUpdatedTS Timestamp(3), primary key (Item_id))

Create table ItemsDetails(Item_id number  not null ,DetailsID NUMBER GENERATED by default on null as IDENTITY ,ItemQuantity number not null,ItemSellingPrice decimal not null,MigratedTS Timestamp(3) default sysdate not null,LastUpdatedTS Timestamp(3) ,primary key (DetailsID),foreign key (Item_id) references Items(Item_id))

Create TABLE ItemsLoadingDetails(LoadingDetails_id NUMBER GENERATED by default on null as IDENTITY,DetailsID number not null ,ItemPaidPricePerPiece decimal not null,storeLoadingDate date default sysdate not null,MigratedTS Timestamp(3) default sysdate not null,LastUpdatedTS Timestamp(3) ,primary key (LoadingDetails_id),foreign key (DetailsID) references ItemsDetails(DetailsID))


Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123687954,'Item1');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123687955,'Item2');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123686956,'Item3');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123684959,'Item4');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123637976,'Item5');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123688001,'Item6');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0963688001,'Item7');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123688002,'Item8');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123688003,'Item9');
Insert  INTO Items (ItemSerialNumber, ItemName) VALUES (0123688001,'Item10');



Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (16,125.65,1)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (13,86.99,2)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (1,25.65,3)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (6,149.99,4)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (16,49.65,5)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (4,1234.65,6)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (1236,1.55,7)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (236,2.99,8)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (12,5.99,9)
Insert  INTO ItemsDetails (ItemQuantity, ItemSellingPrice,Item_ID) VALUES (40,15.99,10)


Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (99.99,1)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (50,2)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (16,3)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (109.99,4)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (35,5)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (899.99,6)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (0.55,7)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (0.99,8)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (2.50,9)
Insert INTO ItemsLoadingDetails (ItemPaidPricePerPiece,DetailsID) VALUES (9.99,10)